development:
  adapter: mysql2
  database: vtracker_development
  username: vtracker
  password:
  host: localhost

test:
  adapter: mysql2
  database: vtracker_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: vtracker
  password:
  host: localhost
